version: 2
jobs:
  build:
    macos:
      xcode: "9.4.0"

    steps:
      - checkout

      - run:
          name: Update submodules
          command: git submodule update --init --recursive

      - run:
          name: Build and run tests
          command: fastlane scan
          environment:
            SCAN_DEVICE: iPhone 8
            SCAN_SCHEME: libSpecta-iOS

      - store_test_results:
          path: test_output
 
      - store_artifacts:
          path: test_output
      
      - store_artifacts:
          path: ~/Library/Logs/scan
          destination: scan-logs
